package models.db

import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime

@DynamoDBTable(tableName = "failed_reservation")
data class FailedReservation(
    @DynamoDBHashKey(attributeName = "reservation_id")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAutoGeneratedKey
    var reservation_id: String? = null,

    @DynamoDBAttribute(attributeName = "user_id")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    var user_id: String,

    @DynamoDBAttribute(attributeName = "reservation_datetime")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    var reservation_datetime: LocalDateTime
)