package models.db

import com.amazonaws.services.dynamodbv2.datamodeling.*
import models.db.type_converter.LocalDateTimeConverter
import java.time.LocalDateTime

@DynamoDBTable(tableName = "failed_reservation")
data class FailedReservation(
    @DynamoDBHashKey(attributeName = "reservation_id")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAutoGeneratedKey
    var reservation_id: String? = null,

    @DynamoDBAttribute(attributeName = "user_id")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    var user_id: String?,

    @DynamoDBAttribute(attributeName = "concert_id")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    var concert_id: Int?,

    @DynamoDBAttribute(attributeName = "reservation_datetime")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
    var reservation_datetime: LocalDateTime?
) {
    constructor() : this(null, null, null, null)
}